### ISSUE TITLE
Aggro Zhar the Mad by Talking to Him Instead of Bookcase

### ISSUE THREAD

**Issue by NiteKat** [diasurgical/devilutionX#1530]
**Important information**
Windows 10 / 1.2.1 / Downloaded release

**Describe**
Zhar can be activated in the attached save by following the steps below.

**To Reproduce**
1. Click on Zhar the Mad and initiate his "What? What are you doing here" dialog. You don't have to let it play through.
2. Use the stairs up to go to floor 7.
3. Use the stairs down to go back to floor 8.
4. Click on Zhar the Mad and he will say the line he should say when you click on the book case, and he will begin to attack you.

**Expected behavior**
On step 4, he should again say his "What? What are you doing here" dialog and not aggro.

**Additional context**
Strangely enough if you aggro him in this fashion and then click the bookcase that should activate him, he'll stop attacking and give the correct speech (Arrrg your curiosity will be the death of you) and then go back to aggroed again. I also tested and going to town does not cause this behavior, it's specifically visiting floor 7 on this save, so I suspect a variable on either Zhar or the bookcase is getting messed up. I also tested skipping step 1, and doing so does not produce this behavior. If you start at step 2, Zhar will give the correct line and drop a book.

[single_2.zip](https://github.com/diasurgical/devilutionX/files/6312579/single_2.zip)

**Comment by AJenbo** [comment]
Sounds like it could be the same sort of issue as with unlocking diablos chamber with only one switch by changing level

**Comment by FitzRoyX** [comment]
I was able to trigger the aggro by just walking some distance away and coming back. I didn't have to leave the dlvl. Are we sure this isn't by design? He does say to stop bothering him, and by talking to him again you're bothering him.

**Comment by qndel** [comment]
Zhar works properly. His quest state changes in 2 situations:
1. You interact with the book and he can see you.
2. You talk with him and he gives you a book, then you lose vision of him = he will aggro next time you talk to him.

The only bug here is being able to trigger his "angry" message twice with these steps:

1. Talk to Zhar and get the book
2. Walk away and lose vision
3. Talk to Zhar again (You got the "angry" message for the first time)
4. Interact with the bookcase while fighting with Zhar = you get his "angry" message for the second time
Fixed by https://github.com/diasurgical/devilutionX/commit/7cc64dd2c49b3f80b0683a003bcf0bab893e4956

**Comment by Chance4us** [comment]
The quest flow still doesn't seem correct to me.
1. Talk to Zhar and get the book
2.  Walk away to the town
3. If you talk to Zhar again, he will fight you, even though you leave the book on the shelf 

Expected behavior:
Zhar shouldn't fight until you take the book off the shelf.

**Comment by AJenbo** [comment]
this looks to be intentional

**Comment by Chance4us** [comment]
> this looks to be intentional

I will retest in vanilla as soon as possible.

**Comment by qndel** [comment]
IT IS intetional. No need to test.
