### ISSUE TITLE
Charging monsters ends up in an invalid state on level change

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#2463]
Unfortunately, I have to report a worrying bug this time because I didn't really know what to look for by bisecting.
As for the history, I can tell that I killed the monsters in the affected level with the Guardians.
When I reentered the level again sometime I noticed the following.

https://user-images.githubusercontent.com/45902449/127213986-8d0d77aa-439c-4052-895c-93c7305ab259.mp4

It is namely a "Frost Charger" that should actually be dead, but information about this is displayed as if he were still alive.
I now hope that one of you has some idea how to find the bug.

Savegame:
[frost_charger.zip](https://github.com/diasurgical/devilutionX/files/6888084/frost_charger.zip)

By the way, is there actually a possibility that this is related to #2441 or #2429 and that other types of monsters could also be affected?

**Comment by AJenbo** [comment]
@obligaron do you think this could be related to the issue we had with MI_Rhino recently?

**Comment by obligaron** [comment]
Yeah it looks kind of similar to #2310
#2310 doesn't fix corrupted game state.
So the question is when / with what version was the level cleared?

And it could also be something different, that we didn't discovered yet. 🤔

**Comment by Chance4us** [comment]
> So the question is when / with what version was the level cleared?

It was played with the following slightly different version.
https://github.com/Chance4us/devilutionX/tree/testing

**Comment by AJenbo** [comment]
Specifically https://github.com/Chance4us/devilutionX/commit/464ba0aaeff5b37ee8bb96f5c7f0f8c5ab0bc7c6 ?

**Comment by NiteKat** [comment]
Does Telekenesis fix the monster?

**Comment by Chance4us** [comment]
> Specifically [Chance4us@464ba0a](https://github.com/Chance4us/devilutionX/commit/464ba0aaeff5b37ee8bb96f5c7f0f8c5ab0bc7c6) ?

It is @qndel's object highlighting with resolved merge conflicts.
https://github.com/diasurgical/devilutionX/pull/2160

**Comment by Chance4us** [comment]
> Does Telekenesis fix the monster?

Unfortunately, I couldn't try it because the hero lacks this spell.

**Comment by FitzRoyX** [comment]
Why one and not the others? Was it the only one to die mid-charge or something?

**Comment by Chance4us** [comment]
As I looked at #2310, unpredictable bugs often arise from cleanups or code style changes that are actually expected to improve.
For example for expected performance improvements or for greater clarity of the code.

Unfortunately, this approach often causes unwanted new bugs and I think that this has happened to us many times.
And these bugs have often been inadvertently caused by a wide variety of very professional programmers,
although they most certainly do not do so on purpose. After all, to err is a quality of all of us.

I'm not a fan of such cleanups unless we used fuzzing to make sure the changes were producing the same results.

What means fuzzing:
https://en.wikipedia.org/wiki/Fuzzing

And as long as we don't use such methods, I suggest that we revert suspicious commits to be absolutely sure.

**Comment by qndel** [comment]
@Chance4us are you sure the charger was dead? There's a vanilla bug that's probably also present in devilutionx where chargers get stuck in a weird invisible/invulnerable state if you change the level while they are charging.

**Comment by AJenbo** [comment]
> As I looked at #2310, unpredictable bugs often arise from cleanups or code style changes that are actually expected to improve.
> For example for expected performance improvements or for greater clarity of the code.
> 
> Unfortunately, this approach often causes unwanted new bugs and I think that this has happened to us many times.
> And these bugs have often been inadvertently caused by a wide variety of very professional programmers,

They have also uncovered and solved other issues. But more importantly if we do not clean it up it will be impossible for us to deal with some of the more fundamental issues.

The cost common places for thease issues to arise is where the code was utilizing hacks or had build in logic errors (like GroupUnity where more then half the code turned out to be dead code that was never called).

> What means fuzzing:
> https://en.wikipedia.org/wiki/Fuzzing
> 
> And as long as we don't use such methods, I suggest that we revert suspicious commits to be absolutely sure.

Anyone is more then welcome to set it up. We already have support for more traditional tests and further testing of it is extremely welcome.

**Comment by AJenbo** [comment]
One of the things that I have been trying to achieve over the past several months is getting the engine in a state where we can record the user input and replay it and have it replicate the same game play from start to finish. This would allow us to have a very comprehensive test since any slight divination would trip up the run which we could then detect. Unfortunately something in the engine is either sensitive to timing or some how not stable in some other way. Solving this would also pretty much be a prerequisite for solving the desync issues in multiplayer. Unfortunately the way the code was written makes it very hard to track down these issues as it could potentially stem from something as simple as uninitialized variables or other bad code.

https://github.com/diasurgical/devilutionX/pull/904

**Comment by StephenCWills** [comment]
> Unfortunately, this approach often causes unwanted new bugs and I think that this has happened to us many times.
> And these bugs have often been inadvertently caused by a wide variety of very professional programmers,
> although they most certainly do not do so on purpose. After all, to err is a quality of all of us.

Making changes to a codebase is basically guaranteed to introduce bugs, whether a professional programmer made them or not. This is a well-known phenomenon in the software industry, and that's why we use so many tools and follow so many guidelines for writing and analyzing code to find or avoid common mistakes. As AJenbo stated just now, the areas of the code where these types of issues crop up tend to be the areas that were already problematic before we touched them. This is not a problem with the process we're using, the people making the changes, or the changes themselves. Rather, it's just a part of the process we'll have to deal with as we progress.

> I'm not a fan of such cleanups unless we used fuzzing to make sure the changes were producing the same results.
> 
> What means fuzzing:
> https://en.wikipedia.org/wiki/Fuzzing
> 
> And as long as we don't use such methods, I suggest that we revert suspicious commits to be absolutely sure.

I don't think it's a good idea to jump the gun on reverting a whole commit just because we suspect it might have caused an issue we're seeing. To fix the issue, it's important to understand why it happens, develop an accurate test case, and then develop a proper solution that fixes the issue for the test case. If we can attribute the issue to a specific change in the codebase, that should actually make it easier to spot the problem, aiding in the process to find the solution. Reverting a change could make that process harder and so should be considered with due caution.

To tie fuzzing back into my main point, fuzzing is a technique that we can use to aid in developing test cases. It can be used to develop the aforementioned test case to assist in finding the solution, or we can use it for other purposes like regression tests. I can imagine that it would be a very welcome addition to the codebase if you could use fuzzing to write some robust test cases for the project. However, I don't think it would be wise to stifle progress on the codebase until we can develop some robust test cases using fuzzing. Fuzzing can be a useful tool, but it is not a necessity.

**Comment by Chance4us** [comment]
> @Chance4us are you sure the charger was dead? There's a vanilla bug that's probably also present in devilutionx where chargers get stuck in a weird invisible/invulnerable state if you change the level while they are charging.

I'm 99% sure he was dead.
It can be said that I've played the game for over 20 years.
And lack of spell alternatives, I literally flooded the affected level with Guardians in this game.
It was a huge fireworks display and a lot of movement and a huge chaos.
And the fireworks lasted until there was complete silence.
But yes of course rhinos can walk around the corner and disappear from view and that I overlook them in rare cases.
So there is still a one percent risk that I missed this one.
On the other hand, if he had become invisible like the Mages (#2441,#2429), then he wouldn't be dead for that reason either.

**Comment by Chance4us** [comment]
I'm especially grateful to you @AJenbo, @qndel and @galaxyhacks,
when you opened the project and rode through the assembler code to ensure the uncompromisingly exact functionality of the original.
And you have invested a great deal of effort, time, patience and sweat in making it as good as it is at the moment.
And I agree with you that these code changes also exposed a lot of problems and I think that's a good thing too.
And I also agree with @StephenCWills that it is important to understand the issues in order to resolve them.
I have addressed the topic in general so that we are all even more careful and the much work that has gone into the project is not in vain.
I will think about how we can avoid bugs.

**Comment by NiteKat** [comment]
> @Chance4us are you sure the charger was dead? There's a vanilla bug that's probably also present in devilutionx where chargers get stuck in a weird invisible/invulnerable state if you change the level while they are charging.

This was why I recommended trying to use telekenesis. If a save file still exists with this situation, you could use a debug build and the cheats from debug to give the character telekenesis.

**Comment by Chance4us** [comment]
> > @Chance4us are you sure the charger was dead? There's a vanilla bug that's probably also present in devilutionx where chargers get stuck in a weird invisible/invulnerable state if you change the level while they are charging.
> 
> This was why I recommended trying to use telekenesis. If a save file still exists with this situation, you could use a debug build and the cheats from debug to give the character telekenesis.

A very unusual idea and yes you were right, Telekinesis brought the poor guy back to life. Can we do something with that?

**Comment by AJenbo** [comment]
... so vanila label for this one :)

**Comment by AJenbo** [comment]
> > @Chance4us are you sure the charger was dead? There's a vanilla bug that's probably also present in devilutionx where chargers get stuck in a weird invisible/invulnerable state if you change the level while they are charging.
> 
> This was why I recommended trying to use telekenesis. If a save file still exists with this situation, you could use a debug build and the cheats from debug to give the character telekenesis.

That actually makes sens, when charging the are put in a "disabled" state and represented by a missile. Changing levels will delete all missiles meaning that the missile will not hit and reposition and activate the actual monster. I guess a fix would be to position any charging at the missile position on level change.

**Comment by Chance4us** [comment]
On the one hand, it's reassuring that we haven't gotten the aggravation I feared.
On the other hand, I feel like an idiot who has no idea about the game and is unpacking loads of vanilla bugs.
@NiteKat, why didn't you say that something like that works right away?

**Comment by NiteKat** [comment]
> On the one hand, it's reassuring that we haven't gotten the aggravation I feared.
> On the other hand, I feel like an idiot who has no idea about the game and is unpacking loads of vanilla bugs.
> @NiteKat, why didn't you say that something like that works right away?

Sorry, I assumed there was already a bug open for the monsters getting stuck like that from charging on this github, since it's been talked about a lot (@qndel made a fix for the Crucible mod for it already). I thought this might be something new, but was suspicious it might be this particular bug. I could have said more in my recommendation for telekenesis though. :)

**Comment by qndel** [comment]
> > There's a vanilla bug that's probably also present in devilutionx where chargers get stuck in a weird invisible/invulnerable state if you change the level while they are charging.
> 
> That actually makes sens, when charging the are put in a "disabled" state and represented by a missile. Changing levels will delete all missiles meaning that the missile will not hit and reposition and activate the actual monster. I guess a fix would be to position any charging at the missile position on level change.

that's a smart fix, in crucible I went with checking all monsters every second, if there's a charger that hasn't changed its position during that time, I unfreeze it

**Comment by AJenbo** [comment]
Can this also happen in other scenarios? Else I'm thinking that checking it on level load would be enough.

**Comment by qndel** [comment]
yeah, I just wanted it to be more "dynamic" in crucible, having to go out and back seemed lame

**Comment by julealgon** [comment]
> ... when charging the are put in a "disabled" state and represented by a missile ...

My god this code man...... what the fuck.

**Comment by FitzRoyX** [comment]
Isn't there a way to process monster specials without adding missiles? It just seems like an inefficient way of handling monsters moving fast.

**Comment by julealgon** [comment]
> Isn't there a way to process monster specials without adding missiles? It just seems like an inefficient way of handling monsters moving fast.

It's likely they did it as a shortcut to get the "effect" running in the game. Since the missile system already provides collision and effects in it, instead of doing it properly, they just repurposed the missile system.

It absolutely should be done differently, but I suspect it won't be that trivial as you'd have to add support for the new behavior "natively" so to speak.

**Comment by galaxyhaxz** [comment]
It shouldn't be too difficult as monsters already have a velocity table. Monsters would still have the missile mode except it would work within the monster code. In this mode you'd set the monsters velocity accordingly and add code to freeze their current frame.

It would also fix the bug @qndel mentioned where leaving a level while they are in missile mode cause them to vanish.

My God is this games code full of hacks xD Good thing they did everything in proper in Diablo 2. But never fear, we'll eventually have a version of d1 just as moddable!!

**Comment by julealgon** [comment]
> Good thing they did everything in proper in Diablo 2.

🤣

**Comment by NiteKat** [comment]
Hmm... just had a thought - we know they freeze like this when you transition floors and they are mid charge, what happens if the missile table is full and they want to start a charge? The reason I'm thinking about this, @Chance4us said they were spamming Guardian to deal with the monsters. Is it possible the Guardians and the firebolts filled up the missile table, this one charger tried to charge, and the result is it's stuck, without a level transition? Pure conjecture, as I have no idea what would happen if a monster starts a charge with the missile table full.

**Comment by obligaron** [comment]
[AddMissile](https://github.com/diasurgical/devilutionX/blob/fe034ce70920b5f4fdaa5ff123437f3669e13403/Source/missiles.cpp#L3083) would return -1 and then [no charge](https://github.com/diasurgical/devilutionX/blob/fe034ce70920b5f4fdaa5ff123437f3669e13403/Source/monster.cpp#L2605) will be performed. 😉 

The problem with reworking this is that this would likely be a breaking change or some work is needed to stay compatible (converting while loading/saving). :neutral_face:

**Comment by julealgon** [comment]
> The problem with reworking this is that this would likely be a breaking change or some work is needed to stay compatible (converting while loading/saving). 😐

We could potentially just keep "accepting" missile-based logic, but for all new attacks not use it. It sucks having to maintain 2 distinct code paths to do the same thing, but it's a possibility 😕 

Either that, or just outright ignore this particular missile type and just handle the monster as active in case loading an old save that still has the missile persisted. It would affect the behavior when loading these saves, but only on this very specific case and the outcome wouldn't be that impactful I think.

**Comment by AJenbo** [comment]
I would be willing to accept this logic moving to monsters, being able to translate the old save game way of doing it, and new save games not being 100% compatible with vanilla (they load but charging monsters can be in an unknown state).
