### ISSUE TITLE
Crash when opening Spellbook as Sorceror when Code=fr

### ISSUE THREAD

**Issue by sixcy** [diasurgical/devilutionX#3793]
Hello,

I was just playing with my nephew earlier, thanks a lot for the french translation it is awesome :)

I found one problem: when playing the Sorceror, when the game is in french (Code=fr), then opening the spellbook results in an immediate crash.

**Comment by AJenbo** [comment]
Since you left out platform and version I'm going to assume that it is Android and version 1.3.0. There is a known bug in the French translation that will cause crashes with 1.3.0. This is a known issue and has been fixed in the latest test builds, but we are holding back releasing the fix as waiting for more uses to migrate from the 

Glad you guys are enjoying the game :)

**Comment by sixcy** [comment]
Thanks for the reply! Sorry for omitting the platform, it was Windows.

Nice to know it has already been fixed. I will probably compile it on my end and give my nephew the fixed executable.

**Comment by sixcy** [comment]
On an unrelated note though, we experienced a weird desync where the my character was stuck in walk animation on his screen. Generally in terms of synchronization it wasn't great, we were playing in physical LAN and I could hear myself double casting on his screen instead of single cast, or blocking something even though I was not blocking anything on my screen, little things like that.

But I never played the original Diablo in physical LAN so perhaps this is part of the original experience. I imagine these things are very hard to reproduce. When you play alone, each person in their house, you probably don't notice it - but when playing in the same room the desync is very noticeable.

That said, it was nothing that stopped us from having loads of fun!

**Comment by AJenbo** [comment]
> Nice to know it has already been fixed. I will probably compile it on my end and give my nephew the fixed executable.

In that case you can just grab the latest test build: https://github.com/diasurgical/devilutionX/suites/4701536620/artifacts/128640185

If you want to go less experimental you can simply replace the deviutionx.mpq with the new one as it contains all the translations.

Regarding dsync, Diablo was always heavily played by such issues. In general we work better then the original. With the one except of the double attack you described. In the original this was rare to happen but the way we implemented holding down the mouse means that it almost always happens. See here for a status on that: https://github.com/diasurgical/devilutionX/issues/2681

**Comment by sixcy** [comment]
This test build does not seem to work: I have "SDL Error, passed a NULL mutex. The error occured at: /home/runner/work/devilutionX/devilutionX/Source/utils/sdl_mutex.h line 39"

I will try to just copy devilutionx.mpq

**Comment by AJenbo** [comment]
Do you encounter the error at launch or at some other point?

**Comment by sixcy** [comment]
Just at launch. But now if I try reverting it to the original 1.3.0 build (just replacing all the files by those from the 1.3.0 release), the issue persists. I will try rebooting, I think something has changed somewhere..

**Comment by sixcy** [comment]
I have no idea what was causing this issue to persist, but its gone (maybe a process that took time to get killed? I should mention that I had to kill devilutionx.exe because the SDL error kept popping up endlessly) - however, I notice that the devilutionx.mpq from the test build you linked is two times lighter than the devilutionx.mpq from the 1.3.0 release; also, it is all in english even though I do still have the "Code=fr" setting.

Perhaps testing builds do not include all languages?

**Comment by qndel** [comment]
> This test build does not seem to work: I have "SDL Error, passed a NULL mutex. The error occured at: /home/runner/work/devilutionX/devilutionX/Source/utils/sdl_mutex.h line 39"
> 
> I will try to just copy devilutionx.mpq

Are you using windows 11?

**Comment by sixcy** [comment]
I am using Windows 10; I am not in the realm of unsupported OS ;)

**Comment by sixcy** [comment]
I should note that the devilutionx.exe from test build keeps overriding diablo.ini to set "Code" to "en" value

**Comment by sixcy** [comment]
I just tried with Hellfire (moving the Hellfire MPQs into the base folder), and somehow it fixes the issue (the crash when opening the spellbook)! So my nephew and I will probably play with the expansion. One more reason to play Hellfire ;)

**Comment by AJenbo** [comment]
indeed, i have added a task for having translations include with most test builds: https://github.com/diasurgical/devilutionX/issues/3801

> I just tried with Hellfire (moving the Hellfire MPQs into the base folder), and somehow it fixes the issue (the crash when opening the spellbook)! So my nephew and I will probably play with the expansion. One more reason to play Hellfire ;)

oh that's right the wording is a bit different for spells in hellfire.

Another option is to grab the [latest translation](https://raw.githubusercontent.com/diasurgical/devilutionX/master/Translations/fr.po), open it in [Poedit](https://poedit.net/download) and hit save. This will generate a fr.mo that you can drop next to the MPQ to have it load that instead.

**Comment by sixcy** [comment]
Nice, I will probably submit some french corrections as PR

**Comment by AJenbo** [comment]
That would be much appreciated :)

**Comment by sixcy** [comment]
Awesome! I just started this here : https://github.com/diasurgical/devilutionX/compare/master...sixcy:patch-1

I will try to get this through - I did not realize there is so much text in Diablo!

**Comment by sixcy** [comment]
I have an update on the crash thing: it still happened, but later in the game. I think it's the Charged Bolt spell that makes it crash - why did not it crash in Hellfire? Simply because I made a new sorcerer, which does not have Lightning Bolt as starting staff (in Hellfire, starting sorcerers have staff of Mana instead)
